on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checks installation script
      - run: ls -la
      - run: sudo chmod u+x
      - run: sudo ./install.sh