on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checks installation script
        run: ls -la
      - name: Grant permissions to necessary files
        run: chmod u+x install.sh
      - name: Run installation script
        run: sudo ./install.sh